"""Best priority found in the 2026-06-01 Codex smoke run.

This priority was generated by `codex_no_finetune` from the 296 seed and
reproducibly builds a 400-element cap set in F_3^8.
"""

import math
import numpy as np


def priority(el, n):
    x = tuple(int(v) % 3 for v in el)

    def ecap4(t):
        a, b, c, d = t
        if a == 0 and b == 0 and c == 0 and d == 0:
            return False
        return (a * a + b * b + c * c + 2 * d * d) % 3 == 0

    def qcap3(a, b, c):
        return c == (a * a + b * b) % 3

    def bcap2(a, b):
        return a != 2 and b != 2

    blocks = [
        (x[0], x[1], x[2], x[3]),
        (x[4], x[5], x[6], x[7]),
    ]

    main1 = ecap4(blocks[0])
    main2 = ecap4(blocks[1])
    main = main1 and main2

    score = 0.0
    if main:
        score += 1000000000.0

    score += 1000000.0 * (main1 + main2)

    alt_parts = [
        ((0, 1, 4, 5), (2, 3, 6, 7)),
        ((0, 2, 4, 6), (1, 3, 5, 7)),
        ((0, 3, 4, 7), (1, 2, 5, 6)),
        ((0, 1, 6, 7), (2, 3, 4, 5)),
        ((0, 2, 5, 7), (1, 3, 4, 6)),
    ]

    alt = 0
    for p, q in alt_parts:
        ep = ecap4(tuple(x[i] for i in p))
        eq = ecap4(tuple(x[i] for i in q))
        alt += 5 * (ep and eq) + ep + eq
    score += 12000.0 * alt

    q1 = qcap3(x[0], x[1], x[2])
    q2 = qcap3(x[3], x[4], x[5])
    q3 = bcap2(x[6], x[7])
    score += 700.0 * (q1 and q2 and q3)
    score += 55.0 * (q1 + q2 + q3)

    wt = sum(1 for v in x if v)
    ones = sum(1 for v in x if v == 1)
    twos = sum(1 for v in x if v == 2)
    s1 = sum(x) % 3
    s2 = sum((i + 1) * x[i] for i in range(n)) % 3
    s3 = sum((i * i + 2 * i + 1) * x[i] for i in range(n)) % 3

    score += 18.0 * (4 - abs(wt - 4))
    score += 7.0 * (ones == twos)
    score += 4.0 * (s1 == 0)
    score += 3.0 * (s2 == 1)
    score += 2.0 * (s3 == 2)

    h = 2166136261
    for i, v in enumerate(x):
        h ^= (i + 19) * (v + 1) * 16777619
        h = (h * 2166136261) & 0xFFFFFFFF
    score += (h / 0xFFFFFFFF) * 0.001

    return score

